version: "3.8"

services:
  mysql:
    image: mysql:8.0.38-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongo:
    image: bitnami/mongodb:7.0.14
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/bitnami/mongodb

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
      - KC_HOSTNAME=localhost
    command: ["start-dev", "--import-realm"]
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
    depends_on:
      - mysql

  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  identity-service:
    build: ./identity-service
    ports:
      - "8080:8080"
    environment:
      - DBMS_CONNECTION=jdbc:mysql://mysql:3306/identity
      - DBMS_USERNAME=root
      - DBMS_PASSWORD=root
    depends_on:
      - mysql
      - kafka
      - keycloak

  workspace-service:
    build: ./workspace-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongo:27017/workspace-service?authSource=admin
    depends_on:
      - mongo

  notification-service:
    build: ./notification-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongo:27017/notification-service?authSource=admin
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
    depends_on:
      - kafka
      - mongo

  api-gateway:
    build: ./api-gateway
    ports:
      - "8888:8888"
    depends_on:
      - identity-service
      - workspace-service
      - notification-service

volumes:
  mysql-data:
  mongo-data: