server:
  port: 8084
  servlet:
    context-path: /unit

spring:
  application:
    name: unit-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3308/unit_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/data-lakehouse

app:
  services:
    identity:
      url: http://localhost:8080/identity